FROM centos:7

COPY postgresql.conf /etc/postgresql/15/main/postgresql.conf
COPY pg_hba.conf /etc/postgresql/15/main/pg_hba.conf
COPY repmgr.conf /




EXPOSE 5432

RUN yum install -y epel-release maven wget
RUN yum clean all
RUN yum install -y  https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN yum install -y postgresql15-server postgresql15-contrib
RUN yum install repmgr_15.x86_64 -y
RUN chown postgres /repmgr.conf
RUN chgrp postgres /repmgr.conf
RUN chmod 777 /repmgr.conf

ENV POD_NAME=podName
#ENV REPMGR_NODE_NAME=abc
#ENV REPMGR_NODE_NETWORK_NAME=172.17.0.2
#ENV REPMGR_NODE_PRIORITY=100
#ENV REPMGR_PRIMARY_HOST=
#ENV REPMGR_PRIMARY_PORT=5432
#ENV REPMGR_PASSWORD=your_replication_password
#ENV REPMGR_CONNECT_TIMEOUT=2
#ENV REPMGR_RECONNECT_ATTEMPTS=6


COPY custom-entrypoint-1.sh /usr/local/bin/custom-entrypoint-1.sh

RUN chmod +x /usr/local/bin/custom-entrypoint-1.sh
ENTRYPOINT ["custom-entrypoint-1.sh"]
CMD ["postgres"]
